name: morphct
channels:
- conda-forge
dependencies:
- blas=*=openblas
- cython=0.29
- ele=0.2.0
- freud=2.6.2
- gsd=2.4.2
- h5py=2.10
- hdf5=1.10
- matplotlib=3.4.2
- numpy=1.21
- openbabel=3.1.1
- pip=21.0.1
- python=3.7
- scipy=1.7
- pytest
- pytest-cov
- pip:
  - git+https://github.com/cmelab/morphct@v0.4.0
  - pyscf
