name: morphct
channels:
- conda-forge
dependencies:
- ele=0.1.0
- freud=2.4.1
- gsd=2.4.0
- matplotlib=3.3.4
- numpy=1.20.1
- openbabel=3.1.1
- pip=21.0.1
- python=3.8.6
- scipy=1.4.1
- pytest
- pytest-cov
- pip:
  - pyscf==1.7.5
